spring:
  datasource:
    url: jdbc:mysql://localhost:3307/project2_db
    username: root
    password: Eniso@23
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

        format_sql: true